###### risk ######
[insider_risk]

###### Legacy Params ######

_name = <string>
    * The name of the summary index where Splunk will write the events.
    * Defaults to "risk".

## Using underscore prepend for risk fields because these are conveniently excluded from the summaryindex markers
## per core implementation of summaryindex alert action in $SPLUNK_HOME/etc/system/default/alert_actions.conf

_insider_risk_score = <int>
    * The score to apply to risk modifiers generated by the implementation of this action
    * Defaults to 1

_insider_risk_object = <string>
    * The field name to use as the risk_object
    * Field must be available in the result set passed to this action
    * Defaults to None

_insider_risk_object_type = [system|user|<string>|other]
    * The type of risk_object
    * Must be one of "system", "user", arbitrary string, or "other"
    * <string> allows for type extensions
    * Defaults to None

###### Modalert Params ######

param.index = <string>
    * The name of the summary index where Splunk will write the events
    * Defaults to "risk"

param._insider_risk = <json>
    * A JSON list of risk object definitions.
    *
    * [
    *     {
    *         "risk_object_field": <risk_object_field>,
    *         "risk_object_type": [system|user|<string>|other],
    *         "risk_score": <risk_score>,
    *         "threat_object_field": <threat_object_field>,
    *         "threat_object_type": <threat_object_types>
    *     }
    *     ...
    * ]
    *
    * Each object requires these three fields (risk_object_field, risk_object_type, risk_score)
    * or these two fields (threat_object_field, threat_object_type). Objects can include both sets of fields.
    * Defaults to None

param._insider_risk_score = <float>
    * The score to apply to risk modifiers generated by the implementation of this action
    * Defaults to 1.0

param._insider_risk_message = <string>
    * The message to be shown for risk, which supports tokens.
    * Defaults to None

param._insider_risk_object = <string>
    * The field name to use as the risk_object
    * Field must be available in the result set passed to this action
    * Defaults to None
    
param._insider_risk_object_type = [system|user|hash_values|network_artifacts|host_artifacts|tools|other|<string>]
    * The type of risk_object
    * Type system allows for asset correlation
    * Type user allows for identity correlation
    * Type <string> allows for type extensions
    * Defaults to None

param.verbose = [true|false|0|1]
    * Set modular alert action logger to verbose mode
    * Defaults to "false"